version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - build_folder:/frontend/dist
      - /frontend/node_modules
    tty: true
    stdin_open: true
    restart: always
    networks:
      - erum

  database:
    container_name: database
    image: mysql:8.0
    env_file:
      - ./backend/.env
    ports:
      - "3307:3306"
    networks:
      - erum

  backend:
    container_name: backend
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - database
    tty: true
    networks:
      - erum

  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/log:/var/log/nginx
      - build_folder:/var/www/frontend
    depends_on:
      - frontend
      - backend
    networks:
      - erum

networks:
  erum:
    driver: bridge

volumes:
  build_folder: {}
